/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        background: 'var(--color-background)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary)',
        'primary-container': 'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        error: 'var(--color-error)',
        'on-error': 'var(--color-on-error)',
        'error-container': 'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        surface: 'var(--color-surface)',
        'on-surface': 'var(--color-on-surface)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-background': 'var(--color-on-background)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'surface-variant': 'var(--color-surface-variant)',
        tertiary: 'var(--color-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        neon: {
          cyan: '#94C5FD',
          blue: '#2763EB',
          purple: '#a855f7',
          pink: '#ec4899',
          green: '#10b981',
          red: '#ff3b3b',
          amber: '#fbbf24',
        },
      },
      fontFamily: {
        caption: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      spacing: {
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'container-max-width': '1200px',
        'sidebar-width': '232px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
      },
      boxShadow: {
        neon: '0 0 20px var(--neon-glow-color, rgba(38, 99, 235, 0.3))',
        'neon-sm': '0 0 10px var(--neon-glow-color, rgba(38, 99, 235, 0.2))',
        'neon-lg': '0 0 40px var(--neon-glow-color, rgba(38, 99, 235, 0.4))',
        'neon-intense': '0 0 20px var(--neon-glow-color, rgba(38, 99, 235, 0.3)), 0 0 60px var(--neon-glow-color, rgba(38, 99, 235, 0.15))',
        glass: '0 8px 32px rgba(0, 0, 0, 0.12)',
        'glass-lg': '0 16px 48px rgba(0, 0, 0, 0.2)',
        'glass-xl': '0 24px 64px rgba(0, 0, 0, 0.25)',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'neon-pulse': 'neon-pulse 3s ease-in-out infinite',
        'neon-pulse-fast': 'neon-pulse 1.5s ease-in-out infinite',
        'glass-shimmer': 'glass-shimmer 3s ease-in-out infinite',
        float: 'float 6s ease-in-out infinite',
        'float-slow': 'float 8s ease-in-out infinite',
        'scan-line': 'scan-line 8s linear infinite',
        'glow-border': 'glow-border 3s ease-in-out infinite',
      },
      keyframes: {
        'neon-pulse': {
          '0%, 100%': { opacity: '1', filter: 'brightness(1)' },
          '50%': { opacity: '0.8', filter: 'brightness(1.2)' },
        },
        'glass-shimmer': {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'scan-line': {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100vh)' },
        },
        'glow-border': {
          '0%, 100%': { borderColor: 'rgba(38, 99, 235, 0.3)' },
          '50%': { borderColor: 'rgba(38, 99, 235, 0.7)' },
        },
      },
    },
  },
  plugins: [],
}
