/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    screens: {
      xs: '480px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        background: 'rgb(var(--rgb-background) / <alpha-value>)',
        primary: 'rgb(var(--rgb-primary) / <alpha-value>)',
        'on-primary': 'rgb(var(--rgb-on-primary) / <alpha-value>)',
        'primary-container': 'rgb(var(--rgb-primary-container) / <alpha-value>)',
        'on-primary-container': 'rgb(var(--rgb-on-primary-container) / <alpha-value>)',
        'on-primary-fixed-variant': 'rgb(var(--rgb-on-primary-fixed-variant) / <alpha-value>)',
        'primary-fixed-dim': 'rgb(var(--rgb-primary-fixed-dim) / <alpha-value>)',
        secondary: 'rgb(var(--rgb-secondary) / <alpha-value>)',
        'on-secondary': 'rgb(var(--rgb-on-secondary) / <alpha-value>)',
        'secondary-container': 'rgb(var(--rgb-secondary-container) / <alpha-value>)',
        'on-secondary-container': 'rgb(var(--rgb-on-secondary-container) / <alpha-value>)',
        error: 'rgb(var(--rgb-error) / <alpha-value>)',
        'on-error': 'rgb(var(--rgb-on-error) / <alpha-value>)',
        'error-container': 'rgb(var(--rgb-error-container) / <alpha-value>)',
        'on-error-container': 'rgb(var(--rgb-on-error-container) / <alpha-value>)',
        surface: 'rgb(var(--rgb-surface) / <alpha-value>)',
        'on-surface': 'rgb(var(--rgb-on-surface) / <alpha-value>)',
        'surface-container': 'rgb(var(--rgb-surface-container) / <alpha-value>)',
        'surface-container-low': 'rgb(var(--rgb-surface-container-low) / <alpha-value>)',
        'surface-container-lowest': 'rgb(var(--rgb-surface-container-lowest) / <alpha-value>)',
        'surface-container-high': 'rgb(var(--rgb-surface-container-high) / <alpha-value>)',
        'surface-container-highest': 'rgb(var(--rgb-surface-container-highest) / <alpha-value>)',
        'on-surface-variant': 'rgb(var(--rgb-on-surface-variant) / <alpha-value>)',
        'on-background': 'rgb(var(--rgb-on-background) / <alpha-value>)',
        outline: 'rgb(var(--rgb-outline) / <alpha-value>)',
        'outline-variant': 'rgb(var(--rgb-outline-variant) / <alpha-value>)',
        'secondary-fixed': 'rgb(var(--rgb-secondary-fixed) / <alpha-value>)',
        'secondary-fixed-dim': 'rgb(var(--rgb-secondary-fixed-dim) / <alpha-value>)',
        'surface-variant': 'rgb(var(--rgb-surface-variant) / <alpha-value>)',
        tertiary: 'rgb(var(--rgb-tertiary) / <alpha-value>)',
        'tertiary-container': 'rgb(var(--rgb-tertiary-container) / <alpha-value>)',
        'tertiary-fixed': 'rgb(var(--rgb-tertiary-fixed) / <alpha-value>)',
        'tertiary-fixed-dim': 'rgb(var(--rgb-tertiary-fixed-dim) / <alpha-value>)',
        'on-tertiary-fixed-variant': 'rgb(var(--rgb-on-tertiary-fixed-variant) / <alpha-value>)',
        'on-tertiary-container': 'rgb(var(--rgb-on-tertiary-container) / <alpha-value>)',
        warning: 'rgb(var(--rgb-warning) / <alpha-value>)',
        'warning-container': 'rgb(var(--rgb-warning-container) / <alpha-value>)',
        'on-warning-container': 'rgb(var(--rgb-on-warning-container) / <alpha-value>)',
        success: 'rgb(var(--rgb-success) / <alpha-value>)',
        'success-container': 'rgb(var(--rgb-success-container) / <alpha-value>)',
        'on-success-container': 'rgb(var(--rgb-on-success-container) / <alpha-value>)',
        neon: {
          cyan: 'rgb(var(--rgb-primary-fixed-dim) / <alpha-value>)',
          blue: 'rgb(var(--rgb-primary) / <alpha-value>)',
          purple: '#8b6f9c',
          pink: '#b5677d',
          green: '#3f8f5f',
          red: '#b42318',
          amber: '#c99a3f',
        },
      },
      fontFamily: {
        sans: ['"Nunito Sans Variable"', 'Nunito Sans', 'system-ui', 'sans-serif'],
        display: ['"Quicksand Variable"', 'Quicksand', 'system-ui', 'sans-serif'],
        caption: ['"Nunito Sans Variable"', 'Nunito Sans', 'system-ui', 'sans-serif'],
        'body-md': ['"Nunito Sans Variable"', 'Nunito Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['"Nunito Sans Variable"', 'Nunito Sans', 'system-ui', 'sans-serif'],
        'label-md': ['"Quicksand Variable"', 'Quicksand', 'system-ui', 'sans-serif'],
        'headline-md': ['"Quicksand Variable"', 'Quicksand', 'system-ui', 'sans-serif'],
        'headline-xl': ['"Quicksand Variable"', 'Quicksand', 'system-ui', 'sans-serif'],
        'headline-lg-mobile': ['"Quicksand Variable"', 'Quicksand', 'system-ui', 'sans-serif'],
        'headline-lg': ['"Quicksand Variable"', 'Quicksand', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      spacing: {
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'container-max-width': '1200px',
        'sidebar-width': '232px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
      },
      boxShadow: {
        neon: '0 1px 2px rgba(15, 23, 42, 0.08)',
        'neon-sm': '0 1px 2px rgba(15, 23, 42, 0.06)',
        'neon-lg': '0 2px 8px rgba(15, 23, 42, 0.10)',
        'neon-intense': '0 2px 8px rgba(15, 23, 42, 0.10)',
        glass: '0 1px 2px rgba(15, 23, 42, 0.06)',
        'glass-lg': '0 2px 8px rgba(15, 23, 42, 0.08)',
        'glass-xl': '0 4px 16px rgba(15, 23, 42, 0.10)',
      },
      backdropBlur: {
        xs: '2px',
      },
      },
  },
  plugins: [],
}
